<?php
require_once 'includes/auth.php'; require_once 'includes/db.php'; $adminId=require_admin();
$errors=[]; $success='';
function clean_field(string $name,int $max): string { $value=trim((string)($_POST[$name] ?? '')); return mb_substr($value,0,$max); }
if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf(); $action=$_POST['action'] ?? '';
  if($action==='add_student'){
    $first=clean_field('first_name',60); $age=clean_field('age_band',40); $interest=clean_field('interest_area',120); $focus=clean_field('current_focus',160); $bio=clean_field('profile_summary',1200); $subject=clean_field('favorite_subject',120); $strengths=clean_field('strengths',180); $aspirations=clean_field('aspirations',180);
    if(!preg_match("/^\p{L}[\p{L}\p{M}'-]{0,59}$/u",$first))$errors[]='Use one approved first name or nickname only—no spaces or surname.';
    if(!in_array($age,['Early primary','Upper primary','Early secondary','Middle secondary','Upper secondary'],true))$errors[]='Choose an age band.';
    foreach([[$interest,'interest area'],[$focus,'current focus'],[$bio,'short biography'],[$subject,'favorite subject'],[$strengths,'strengths'],[$aspirations,'aspirations']] as [$value,$label])if($value==='')$errors[]='Add the '.$label.'.';
    if(!$errors){ $ascii=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$first); $slug=preg_replace('/[^a-z0-9]+/','-',strtolower($ascii ?: 'student')); $code=trim($slug,'-').'-'.bin2hex(random_bytes(3)); $stmt=db()->prepare('INSERT INTO student_journeys(public_code,first_name,display_name,age_band,interest_area,current_focus,profile_summary,favorite_subject,strengths,aspirations,active) VALUES(?,?,?,?,?,?,?,?,?,?,1)'); $stmt->execute([$code,$first,$first,$age,$interest,$focus,$bio,$subject,$strengths,$aspirations]); $success=$first.' is now available for sponsorship.'; }
  }elseif($action==='add_update'){
    $journeyId=(int)($_POST['student_journey_id'] ?? 0); $title=clean_field('title',180); $summary=clean_field('summary',1800); $milestone=clean_field('milestone',120);
    $check=db()->prepare('SELECT first_name FROM student_journeys WHERE id=?'); $check->execute([$journeyId]); $studentName=$check->fetchColumn();
    if(!$studentName)$errors[]='Choose a valid student.'; if($title==='' || $summary==='' || $milestone==='')$errors[]='Complete the update title, milestone, and summary.';
    if(!$errors){ $stmt=db()->prepare('INSERT INTO student_updates(student_journey_id,title,summary,milestone,is_sample,published_at,visible) VALUES(?,?,?,?,0,NOW(),1)'); $stmt->execute([$journeyId,$title,$summary,$milestone]); $success='The reviewed update for '.$studentName.' is now visible to sponsors.'; }
  }elseif($action==='toggle_student'){
    $journeyId=(int)($_POST['student_journey_id'] ?? 0); $active=(int)($_POST['active'] ?? 0)===1?1:0; $stmt=db()->prepare('UPDATE student_journeys SET active=? WHERE id=?'); $stmt->execute([$active,$journeyId]); $success=$active?'The student is available for selection.':'The student has been hidden from new sponsorship selection.';
  }
}
$students=db()->query('SELECT j.*,(SELECT COUNT(*) FROM sponsorships s WHERE s.student_journey_id=j.id) sponsor_count,(SELECT COUNT(*) FROM student_updates u WHERE u.student_journey_id=j.id AND u.visible=1) update_count FROM student_journeys j ORDER BY j.active DESC,j.first_name')->fetchAll();
$pageTitle='Student Administration'; $pageDescription='Protected tools for managing sponsorship profiles and student updates.'; include 'includes/header.php';
?>
<section class="dashboard-hero"><div class="wrap dashboard-head"><div><span class="eyebrow light">Protected administration</span><h1>Student profiles and updates.</h1><p>Create privacy-safe sponsorship profiles and publish reviewed learning updates.</p></div><a class="button button-light" href="portal.php">Return to dashboard</a></div></section>
<section class="section cream"><div class="wrap">
<div class="admin-warning"><strong>First names only.</strong><span>Use an approved first name or public nickname. Never enter a surname, birthdate, school, address, phone number, family hardship, medical information, or private contact details.</span></div>
<?php if($success): ?><div class="alert success" role="status"><?= htmlspecialchars($success) ?></div><?php endif; ?><?php if($errors): ?><div class="alert error" role="alert"><strong>Please review:</strong><ul><?php foreach($errors as $error): ?><li><?= htmlspecialchars($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<div class="admin-grid"><section class="form-card"><span class="eyebrow">Add a student</span><h2>Create a selectable profile</h2><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="action" value="add_student"><div class="form-grid"><label>Public first name or nickname<input name="first_name" maxlength="60" required placeholder="First name only"><small>No spaces or surname</small></label><label>Age band<select name="age_band" class="select-input" required><option value="">Choose one</option><option>Early primary</option><option>Upper primary</option><option>Early secondary</option><option>Middle secondary</option><option>Upper secondary</option></select></label><label class="wide">Short approved biography<textarea name="profile_summary" maxlength="1200" rows="5" required placeholder="Describe personality, learning interests, and growth in dignity-centered language."></textarea></label><label>Interest area<input name="interest_area" maxlength="120" required placeholder="Creative coding and design"></label><label>Favorite subject<input name="favorite_subject" maxlength="120" required placeholder="Mathematics"></label><label class="wide">Current learning focus<input name="current_focus" maxlength="160" required placeholder="Building a first web page"></label><label class="wide">Strengths<input name="strengths" maxlength="180" required placeholder="Curiosity, teamwork, and persistence"></label><label class="wide">Aspirations<input name="aspirations" maxlength="180" required placeholder="Create a useful community technology project"></label></div><button class="button full" type="submit">Add student profile</button></form></section>
<section class="form-card"><span class="eyebrow">Publish an update</span><h2>Add a learning milestone</h2><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="action" value="add_update"><label>Student<select name="student_journey_id" class="select-input" required><option value="">Choose a student</option><?php foreach($students as $student): ?><option value="<?= (int)$student['id'] ?>"><?= htmlspecialchars($student['first_name']) ?></option><?php endforeach; ?></select></label><label>Milestone<input name="milestone" maxlength="120" required placeholder="Project completed"></label><label>Update title<input name="title" maxlength="180" required placeholder="A first web page takes shape"></label><label>Reviewed update summary<textarea name="summary" maxlength="1800" rows="7" required placeholder="Share verified learning progress without private or identifying details."></textarea></label><button class="button full" type="submit">Publish sponsor update</button></form></section></div>

<section class="admin-list"><div><span class="eyebrow">Current profiles</span><h2>Students available to sponsors</h2></div><div class="admin-students"><?php foreach($students as $student): ?><article><div class="admin-avatar" aria-hidden="true"><?= htmlspecialchars(mb_strtoupper(mb_substr($student['first_name'],0,1))) ?></div><div><span class="journey-band"><?= htmlspecialchars($student['age_band']) ?></span><h3><?= htmlspecialchars($student['first_name']) ?></h3><p><?= htmlspecialchars($student['profile_summary']) ?></p><small><?= (int)$student['sponsor_count'] ?> sponsorships · <?= (int)$student['update_count'] ?> updates</small></div><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><input type="hidden" name="action" value="toggle_student"><input type="hidden" name="student_journey_id" value="<?= (int)$student['id'] ?>"><input type="hidden" name="active" value="<?= (int)$student['active']===1?0:1 ?>"><button class="button <?= (int)$student['active']===1?'button-outline':'' ?>" type="submit"><?= (int)$student['active']===1?'Hide from selection':'Make selectable' ?></button></form></article><?php endforeach; ?></div></section>
</div></section>
<?php include 'includes/footer.php'; ?>
