<?php
$pageTitle='AD2 Alumni Foundation Partnership';
$pageDescription='Learn about the AD² alumni legacy and its partnership with Mill Creek-AR Learning Center.';
include 'includes/header.php';
?>
<section class="page-hero"><div class="wrap"><span class="eyebrow">Our foundation partner</span><h1>The AD² alumni legacy behind the partnership.</h1><p class="lede">A tradition shaped at Louisiana Tech University—connecting scholarship, technical excellence, perseverance, mentorship, and service across generations.</p></div></section>

<section class="section"><div class="wrap grid-2"><div><span class="eyebrow">What AD² means</span><h2>Alpha Delta Delta—truly “squared.”</h2><p>AD² is the familiar name of the Alpha Delta Delta Chapter of Omega Psi Phi Fraternity, Inc. at Louisiana Tech University in Ruston. The chapter was officially chartered on December 7, 1985, after an organizing history that began in the 1970s.</p><p>According to the Omega Psi Phi Ninth District’s chapter history, Alpha Delta Delta was the first three-letter undergraduate chapter in the fraternity. With Louisiana Tech’s technical focus and many members studying engineering and science, alumni shortened Alpha Delta Delta to AD²—a name that joined chapter identity with the language of mathematics and technology.</p><div class="pull-quote">An alumni tradition of scholarship and uplift now helps build a technology-learning bridge from Mill Creek to Accra.</div></div><div class="foundation-badge"><img src="assets/images/brand-mark.svg" alt="" width="110" height="110"><span>AD² Alumni Foundation</span><small>Educational partnership · Alumni service · Youth opportunity</small></div></div></section>

<section class="section cream"><div class="wrap"><div class="statement"><span class="eyebrow">A record of educational service</span><h2>Learning, mentoring, and community uplift are part of the tradition.</h2><p class="lede" style="margin-inline:auto">Archived Ninth District publications document Alpha Delta Delta members sharing college, vocational, financial-aid, and STEM information with families; mentoring local students; and supporting community education activities.</p></div><div class="grid-3" style="margin-top:45px"><article class="impact-card"><span class="number">Learn</span><h3>Scholarship</h3><p>Encouraging young people to see education as a practical route to wider choices.</p></article><article class="impact-card"><span class="number">Guide</span><h3>Mentorship</h3><p>Showing up consistently as role models, listeners, and advocates for student growth.</p></article><article class="impact-card"><span class="number">Lift</span><h3>Service</h3><p>Turning alumni experience and professional networks into meaningful community support.</p></article></div></div></section>

<section class="section forest"><div class="wrap grid-2"><div><span class="eyebrow light">How the partnership is designed to work</span><h2>Vision with structure behind it.</h2><p class="lede" style="color:#d7e3df">Mill Creek-AR Learning Center brings the local educational vision. The AD² Alumni Foundation partnership is intended to strengthen the support system around that vision.</p></div><div><ul class="value-list"><li><strong>Stewardship</strong><span>Build clear donation, budgeting, and reporting practices around the project.</span></li><li><strong>Alumni engagement</strong><span>Invite mentors and technical professionals to contribute relevant experience.</span></li><li><strong>Continuity</strong><span>Help the learning center plan for sustained instruction rather than one-time activity.</span></li><li><strong>Accountability</strong><span>Publish verified goals, program updates, and financial information as the initiative develops.</span></li></ul></div></div></section>

<section class="section"><div class="wrap grid-2"><div><span class="eyebrow">Transparency before launch</span><h2>Donors should know who is responsible for what.</h2><p>Public nonprofit directories identify the AD2 Alumni Foundation in Rowlett, Texas and categorize it as an educational/youth-development organization. Before live fundraising begins, the site will add foundation-confirmed tax status, official contact information, leadership, donation policies, and reporting commitments.</p><p>This learning-center partnership does not imply endorsement by Louisiana Tech University, Omega Psi Phi Fraternity, Inc., or the film <em>Akeelah and the Bee</em>.</p></div><div class="source-list"><h3>Public references</h3><a href="https://www.mightyninth.com/chapter_page.php?ChapterNumber=310&amp;title=Alpha+Delta+Delta" target="_blank" rel="noopener">Omega Psi Phi Ninth District: Alpha Delta Delta chapter history <span aria-hidden="true">↗</span></a><a href="https://www.mightyninth.com/Documents/Publications/The%20Source/The%20Source%20-%20Vol.%2020%281%29%20Spring%202011.pdf" target="_blank" rel="noopener">Ninth District archive: education and mentoring activities <span aria-hidden="true">↗</span></a><a href="https://www.spotfund.com/organization/b1673a46-973f-4231-9acf-f327065a531e" target="_blank" rel="noopener">Public nonprofit directory listing <span aria-hidden="true">↗</span></a></div></div></section>
<?php include 'includes/footer.php'; ?>
