<?php
require_once 'includes/auth.php'; require_once 'includes/db.php'; $userId=require_user();
$stmt=db()->prepare('SELECT id,first_name,last_name,email FROM users WHERE id=?'); $stmt->execute([$userId]); $user=$stmt->fetch(); if(!$user){ logout_user(); header('Location: login.php'); exit; }
$stmt=db()->prepare('SELECT s.*,j.display_name,j.age_band,j.interest_area,j.current_focus,j.public_code FROM sponsorships s JOIN student_journeys j ON j.id=s.student_journey_id WHERE s.user_id=? ORDER BY s.created_at DESC'); $stmt->execute([$userId]); $sponsorships=$stmt->fetchAll();
$pageTitle='My Sponsor Dashboard'; $pageDescription='View your sponsorship status and student learning updates.'; include 'includes/header.php';
?>
<section class="dashboard-hero"><div class="wrap dashboard-head"><div><span class="eyebrow light">Sponsor dashboard</span><h1>Welcome, <?= htmlspecialchars($user['first_name']) ?>.</h1><p>Your giving status and learning updates are together in one simple place.</p></div><form method="post" action="logout.php"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><button class="button button-light" type="submit">Sign out</button></form></div></section>
<section class="section cream"><div class="wrap">
<?php if(!$sponsorships): ?><div class="empty-state"><span aria-hidden="true">↗</span><h2>No sponsorships yet</h2><p>Choose a privacy-safe student journey to begin.</p><a class="button" href="adopt.php">Choose a journey</a></div>
<?php else: ?><div class="dashboard-layout"><aside class="dashboard-summary"><span class="eyebrow">Your giving</span><strong class="summary-number"><?= count($sponsorships) ?></strong><span><?= count($sponsorships)===1?'supported journey':'supported journeys' ?></span><p>Payment status changes only after confirmation from the secure payment provider.</p><a class="button button-outline" href="adopt.php">Support another journey</a></aside><div class="sponsorship-stack">
<?php foreach($sponsorships as $sponsorship): $up=db()->prepare('SELECT * FROM student_updates WHERE student_journey_id=? AND visible=1 ORDER BY published_at DESC'); $up->execute([$sponsorship['student_journey_id']]); $updates=$up->fetchAll(); ?>
<article class="sponsorship-panel"><header><div><span class="journey-band"><?= htmlspecialchars($sponsorship['age_band']) ?></span><h2><?= htmlspecialchars($sponsorship['display_name']) ?></h2><p><?= htmlspecialchars($sponsorship['current_focus']) ?></p></div><span class="status-pill status-<?= htmlspecialchars($sponsorship['status']) ?>"><?= htmlspecialchars(ucfirst($sponsorship['status'])) ?></span></header><div class="donation-status"><div><small>Contribution</small><strong>$<?= number_format((float)$sponsorship['amount'],2) ?> <?= $sponsorship['frequency']==='monthly'?'/ month':'one time' ?></strong></div><div><small>Payment method</small><strong><?= htmlspecialchars(ucfirst($sponsorship['payment_provider'])) ?></strong></div><div><small>Started</small><strong><?= date('M j, Y',strtotime($sponsorship['created_at'])) ?></strong></div></div><div class="sample-banner"><strong>Starter updates</strong> These examples demonstrate the dashboard. Program staff must replace them with reviewed, verified updates before launch.</div><section class="updates"><h3>Learning updates</h3><?php if(!$updates): ?><p>No updates have been published yet.</p><?php else: ?><div class="timeline"><?php foreach($updates as $update): ?><article><time datetime="<?= htmlspecialchars($update['published_at']) ?>"><?= date('M j, Y',strtotime($update['published_at'])) ?></time><span><?= htmlspecialchars($update['milestone'] ?? 'Learning update') ?></span><h4><?= htmlspecialchars($update['title']) ?></h4><p><?= htmlspecialchars($update['summary']) ?></p></article><?php endforeach; ?></div><?php endif; ?></section></article>
<?php endforeach; ?></div></div><?php endif; ?>
<div class="privacy-note"><strong>Student privacy:</strong> Dashboard updates report learning progress only. Sponsors do not receive full names, school details, family information, private messages, or direct contact access.</div></div></section>
<?php include 'includes/footer.php'; ?>
